upravujem aby mi sli testy

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -6,9 +6,12 @@ export POSIXLY_CORRECT=yes
 export LC_ALL=C
 
 # odstranit
-export MOLE_RC="$HOME"/.config/molerc
-EDITOR="nano"
-VISUAL="code"
+#export MOLE_RC="$HOME"/.config/molerc
+#EDITOR="nano"
+#VISUAL="code"
+
+DATETIME=$($BINL/testdate)
+#DATETIME=$(date +%Y-%m-%d_%H-%M-%S)
 
 
 
@@ -50,12 +53,16 @@ getdir(){
   fi
 }
 
+
+
+
 log_mole_rc(){
   getdir
   if [ -z "$GROUP" ];then
     GROUP="-"
   fi
-  echo "$DATETIME;$USER;$GROUP;$DIR;$FILE;$(realpath "$FILE")" >> "$MOLE_RC"
+  NAME=$(basename "$FILE")
+  echo "$DATETIME;$USER;$GROUP;$DIR;$NAME;$(realpath "$FILE")" >> "$MOLE_RC"
 } 
 
 
@@ -77,14 +84,14 @@ echo "$FILTERED" | awk -F ';' '{print $6 ";" $1}' \
       {
         if ($1 != last_file) {
           if (last_file != "") {
-            print concat
+            print date
           }
           last_file = $1
-          concat = $1 ";"
+          date = $1 ";"
         }
-        concat = concat $2 ";"
+        date = date $2 ";"
       }
-      END {if (last_file != "") print concat}' \
+      END {if (last_file != "") print date}' \
   | bzip2 -c > "$SL_PATH"/"$FILENAME".bz2
 
 
@@ -101,7 +108,7 @@ check_date_format() {
 
 
 filter_data(){
-
+  getdir
   if [ "$DIR" ]; then
     FILTERED=$(awk -F';' -v dir="$DIR" '$4 == dir {print}' "$MOLE_RC")
   fi
@@ -132,10 +139,10 @@ filter_data(){
     FILTERED=$(echo "$FILTERED" | awk -F';' -v date="$DATE_BEFORE" '{split($1, dt, "_"); if (dt[1] > date) print}') 
   fi
  
-  if [ -z "$FILTERED" ] && [ -z "$SECRETLOG" ]; then
-    echo "No files edited through mole were found with specified criteria"
-    exit 0
-  fi
+  #if [ -z "$FILTERED" ] && [ -z "$SECRETLOG" ]; then
+  #  echo "No files edited through mole were found with specified criteria"
+  #  exit 1
+  #fi
 }
 
 list(){
@@ -147,14 +154,20 @@ list(){
 }
 
 change_dir() {
-  
-  if [ "$FILE" ]; then
-    { cd "$(realpath "$FILE")" || { echo "Could not open $FILE"; exit 1; } }
+
+  DIR=$(dirname $(awk -v file="$(basename $FILE)" -F';' '$5 == file { print $6 }' "$MOLE_RC" | tail -1))
+  echo $DIR
+  if [ -z "$DIR" ]; then
+    echo "ERROR: "
+    exit 1
   fi
 
-  getdir
-
+  cd "$DIR" ||{ 
+    echo "Could not open directory $DIR";
+    exit 1;} 
+  #getdir
   filter_data
+  
 
   if [ "$MOST_USED" ]; then
     FILE=$(echo "$FILTERED" | awk -F';' '{print $5}' | sort | uniq -c | sort -rn | head -n 1 | awk '{print $2}')
@@ -162,7 +175,6 @@ change_dir() {
     LAST_USED=$(echo "$FILTERED" | tail -n 1 | awk -F ';' '{print $5}')
     FILE="$LAST_USED"
   fi
-  
   open_file 
 }
 
@@ -173,13 +185,12 @@ open_file() {
     exit 1
   fi
   
-  open_editor "$FILE"
+  open_editor $(basename "$FILE")
   if [ $? -ne 0 ]; then
     echo ERROR: Could not open editor
     exit 1
   fi
   log_mole_rc
-
 }
 
 
@@ -202,7 +213,8 @@ if [ ! -f "$MOLE_RC" ]; then
 fi
 
 #DATE=$(date +%Y-%m-%d)
-DATETIME=$(date +%Y-%m-%d_%H-%M-%S)
+#DATETIME=$($BINL/testdate)
+#DATETIME=$(date +%Y-%m-%d_%H-%M-%S)
 
 
 if [ "$1" = "list" ]; then
@@ -254,17 +266,34 @@ if [ "$SECRETLOG" ]; then
   exit 0
 fi
 
-  
-if [ $# -ne 0 ]; then
-  FILE=$1
-  shift
-  if [ -d "$FILE" ]; then 
-    change_dir
-  else
-    open_file "$GROUP" "$FILE"
-  fi
+
+if [ $# -eq 0 ]; then
+  current_dir=$(realpath .)  
 else
-  change_dir
+  ARGUMENT=$(realpath $1)
+  if [ -d "$ARGUMENT" ]; then
+    current_dir=$ARGUMENT
+  else
+    FILE=$ARGUMENT
+    open_file
+    exit 0
+  fi
+  shift
 fi
+
+
+# otvori v editore posledny editovany subor v tomto adresari
+# regulerny vyraz sub(/\/[^\/]*$/, "", $6) odstrani vsetko po poslednom '/' -> ziska cestu k suboru
+# ziskanu cestu porovna s aktualnym adresarom, ak je rovnaky -> otvori subor
+FILE=$(awk -v current_dir="$current_dir" -F ';' '{original=$6; sub(/\/[^\/]*$/, "", $6); if ($6 == current_dir) {last_match=original}} END {print last_match}' "$MOLE_RC")
+
+# ak sa nenajde ziadna zhoda, ukonci skript s errorom
+if [ -z "$FILE" ]; then
+  echo "No files were edited with mole in this directory"
+  exit 1
+fi
+
+#echo "$FILE"
+open_file
 
 exit 0
