list sorting with filters

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -46,7 +46,6 @@ open_editor() {
 getdir(){
   if [ -z "$FILE" ]; then
     DIR=$(basename "$(realpath .)")
-    echo $DIR
   else
     DIR=$(basename "$(dirname "$(realpath "$FILE")")")
   fi
@@ -57,8 +56,37 @@ log_mole_rc(){
   echo "$DATETIME,$USER,$GROUP,$DIR,$FILE" >> "$MOLE_RC"
 } 
 
+check_date_format() {
+  if ! echo "$1" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
+    echo "Invalid date format"
+    echo "The correct format of date is YYYY-MM-DD"
+    exit 1
+  fi
+}
+
 list(){
-  SORTED=$(sort -f -t ',' -k5 "$MOLE_RC")
+  FILTERED=$(awk -F',' -v dir="$DIR" '$4 == dir {print}' "$MOLE_RC")
+
+  if [ "$GROUP" ]; then
+    FILTERED=$(echo "$FILTERED" | awk -F',' -v dir="$GROUP" '$3 == dir {print}')
+  fi
+
+  if [ "$DATE_AFTER" ]; then
+    check_date_format "$DATE_AFTER"
+    FILTERED=$(echo "$FILTERED" | awk -F',' -v date="$DATE_AFTER" '$1 > date {print}')
+  fi
+
+  if [ "$DATE_BEFORE" ];then
+    check_date_format "$DATE_BEFORE"
+    FILTERED=$(echo "$FILTERED" | awk -F',' -v date="$DATE_BEFORE" '$1 < date {print}')  
+  fi
+ 
+  if [ -z "$FILTERED" ]; then
+    echo "No files edited through mole were found with specified criteria"
+    exit 0
+  fi
+
+  SORTED=$(echo "$FILTERED" | sort -f -t ',' -k5 -k3)
   LONGESTNAME=$(awk -F ',' '{ if (length($5) > max) max=length($5) } END { print max }' "$MOLE_RC")
   LONGESTNAME=$((LONGESTNAME+1))
   echo "$SORTED" | awk -F ',' '{printf "%-'$LONGESTNAME's %s\n", $5":", $3}'
@@ -72,13 +100,12 @@ change_dir() {
 
 
   getdir
-  FILTERED_BY_DIR=$(awk -F',' -v dir="$DIR" '$4 == dir {print}' "$MOLE_RC")
+  FILTERED=$(awk -F',' -v dir="$DIR" '$4 == dir {print}' "$MOLE_RC")
 
   if [ "$MOST_USED" ]; then
-    FILE=$(echo "$FILTERED_BY_DIR" | awk -F',' '{print $5}' | sort | uniq -c | sort -rn | head -n 1 | awk '{print $2}')
-    echo "MOST USED FILE: $FILE"
+    FILE=$(echo "$FILTERED" | awk -F',' '{print $5}' | sort | uniq -c | sort -rn | head -n 1 | awk '{print $2}')
   else 
-    LAST_USED=$(echo "$FILTERED_BY_DIR" | tail -n 1 | awk -F ',' '{print $5}')
+    LAST_USED=$(echo "$FILTERED" | tail -n 1 | awk -F ',' '{print $5}')
     FILE="$LAST_USED"
   fi
   
@@ -97,6 +124,9 @@ open_file() {
     chgrp "$GROUP" "$FILE"
   else
     GROUP=$(id -gn)
+    if [ -z "$GROUP" ]; then
+      GROUP="-"
+    fi
   fi
 
   open_editor "$FILE"
@@ -119,10 +149,7 @@ if [ -z "$MOLE_RC" ]; then
   exit 1
 fi
 
-if [ -f "$MOLE_RC" ]; then
-  #echo "nasiel som $MOLE_RC"
-  echo
-else
+if [ ! -f "$MOLE_RC" ]; then
   mkdir -p "$(dirname "$MOLE_RC")"
   touch "$MOLE_RC"
 fi
@@ -130,7 +157,6 @@ fi
 #DATE=$(date +%Y-%m-%d)
 DATETIME=$(date +%Y-%m-%d\ %H:%M:%S)
 
-#echo "$DATE"
 
 if [ "$1" = "list" ]; then
   LIST="TRUE"
@@ -141,11 +167,13 @@ fi
 #reset OPTIND
 OPTIND=1
 # parse arguments
-while getopts ":hg:m" option; do
+while getopts ":hg:ma:b:" option; do
   case "$option" in
   h)      print_help; exit 1;;
   g)      GROUP=$OPTARG;;
   m)      MOST_USED="TRUE";;
+  a)      DATE_AFTER=$OPTARG;; #YYYY-MM-DD format
+  b)      DATE_BEFORE=$OPTARG;; #YYYY-MM-DD format
   :)      echo "Error: -$OPTARG requires an argument"; exit 1;;
   *)      echo "Invalid option: -$OPTARG" >&2
           echo "Try 'mole -h' for more information."
@@ -155,7 +183,13 @@ done
 
 shift $((OPTIND-1))
 
+
 if [ "$LIST" ]; then
+  if [ $# -ne 0 ]; then
+    DIR=$1
+  else 
+    getdir
+  fi
   list
   exit 0
 fi
